{% set version = "2.0.4" %}

package:
  name: libjpeg-turbo
  version: {{ version }}

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ version }}.tar.gz
  sha256: 9310613182cb617ce300a4079bc7fa13f2f31a99c12601af47f77657c0dd8537

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - msinttypes  # [win and py<35]
    - yasm
    - jom  # [win]

outputs:
  - name: libjpeg-turbo
    build:
      run_exports:
      - {{ pin_subpackage('libjpeg-turbo', max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - cmake
        - make
        - msinttypes  # [win and py<35]
        - yasm
        - jom  # [win]

    test:
      files:
        - testorig.jpg
      commands:
        - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

    about:
      summary: IJG JPEG compliant runtime library with SIMD and other optimizations

  - name: jpeg
    version: 8d
    build:
      run_exports:
        - {{ pin_subpackage('jpeg') }}
      track_features:
        - jpeg_impl_libjpeg_turbo
    requirements:
      run:
        - {{ pin_subpackage('libjpeg-turbo', exact=True) }}
    about:
      summary: jpeg virtual package

about:
  home: http://www.libjpeg-turbo.org/
  license: IJG, modified 3-clause BSD and zlib
  license_file: LICENSE.md
  summary: IJG JPEG compliant runtime library with SIMD and other optimizations

extra:
  recipe-maintainers:
    - valgur
    - sdvillal
